# Generated by Django 4.2.5 on 2023-12-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_trucks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trucks',
            new_name='Truck',
        ),
    ]
